server:
  port: 9090
spring:
  cloud:
    gateway:
      routes:
        - id: greeting_service_v1
          uri: 'http://localhost:8081'
          predicates:
            - Path=/greeting/**
            - Query=src,mobile
        - id: greeting_service_v2
          uri: 'http://localhost:8082'
          predicates:
            - Path=/greeting/**
